version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"